version: "3"

services:
  Goauth:
    image: usman/go-auth:${GO_AUTH_VERSION:-latest}
    ports:
      - "9000:9000"
    command:
      - "-l"
      - "debug"
      - "run"
      - "--db-host"
      - "db"
      - "-p"
      - "9000"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: messenger
      MYSQL_USER: messenger
      MYSQL_PASSWORD: messenger

      