Goauth:
  image: usman/go-auth
  ports:
    - "9000:9000"
  stdin_open: true
  links:
    - Database:db
  command:
    - "-l"
    - "debug"
    - "-t"
    - "console"
    - "run"
    - "--db-host"
    - "db"
    - "-p"
    - "9000"
  tty: true

Database:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: rootpass
    MYSQL_DATABASE: messenger
    MYSQL_USER: messenger
    MYSQL_PASSWORD: messenger
  expose:
    - "3306"
  ports:
    - "3306:3306"
  stdin_open: true
  tty: true

